<?php

namespace App\Http\Controllers;


use App\Http\Controllers\AdminController;
use App\Page;


class TestClass extends AdminController{

    protected $model = '\App\Page';

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}
